/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutAdminFrontIndexImport } from './routes/_layout/admin/front/index'
import { Route as LayoutAdminFrontIdImport } from './routes/_layout/admin/front/$id'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminFrontIndexRoute = LayoutAdminFrontIndexImport.update({
  path: '/admin/front/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminFrontIdRoute = LayoutAdminFrontIdImport.update({
  path: '/admin/front/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/front/$id': {
      id: '/_layout/admin/front/$id'
      path: '/admin/front/$id'
      fullPath: '/admin/front/$id'
      preLoaderRoute: typeof LayoutAdminFrontIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/front/': {
      id: '/_layout/admin/front/'
      path: '/admin/front'
      fullPath: '/admin/front'
      preLoaderRoute: typeof LayoutAdminFrontIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutIndexRoute,
    LayoutAdminFrontIdRoute,
    LayoutAdminFrontIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/admin/front/$id",
        "/_layout/admin/front/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/front/$id": {
      "filePath": "_layout/admin/front/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/front/": {
      "filePath": "_layout/admin/front/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
