/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutDonateImport } from './routes/_layout/donate'
import { Route as LayoutAdminFrontSplitsIndexImport } from './routes/_layout/admin/front/splits/index'
import { Route as LayoutAdminFrontSplitsIdImport } from './routes/_layout/admin/front/splits/$id'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDonateRoute = LayoutDonateImport.update({
  path: '/donate',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminFrontSplitsIndexRoute =
  LayoutAdminFrontSplitsIndexImport.update({
    path: '/admin/front/splits/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutAdminFrontSplitsIdRoute = LayoutAdminFrontSplitsIdImport.update({
  path: '/admin/front/splits/$id',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/donate': {
      id: '/_layout/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof LayoutDonateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/front/splits/$id': {
      id: '/_layout/admin/front/splits/$id'
      path: '/admin/front/splits/$id'
      fullPath: '/admin/front/splits/$id'
      preLoaderRoute: typeof LayoutAdminFrontSplitsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/front/splits/': {
      id: '/_layout/admin/front/splits/'
      path: '/admin/front/splits'
      fullPath: '/admin/front/splits'
      preLoaderRoute: typeof LayoutAdminFrontSplitsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutDonateRoute,
    LayoutIndexRoute,
    LayoutAdminFrontSplitsIdRoute,
    LayoutAdminFrontSplitsIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/donate",
        "/_layout/",
        "/_layout/admin/front/splits/$id",
        "/_layout/admin/front/splits/"
      ]
    },
    "/_layout/donate": {
      "filePath": "_layout/donate.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/front/splits/$id": {
      "filePath": "_layout/admin/front/splits/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/front/splits/": {
      "filePath": "_layout/admin/front/splits/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
